"""initial schema

OSSリリースにあたり、これまでの全マイグレーションを1本に統合したもの。最終的なテーブル定義は
SQLAlchemyモデル(app.models)から自動生成しており、旧チェーンを順に適用した場合と同一のスキーマに
なる(alembic autogenerate/checkで差分ゼロを確認済み)。

Revision ID: 0001
Revises:
Create Date: 2026-09-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reserved >= 0', name='ck_assemblies_reserved'),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name='ck_assemblies_unit_cost'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_alert_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('first_triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('reorder_threshold', 'po_overdue', 'buildable_threshold')", name='ck_notification_alert_states_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('group', sa.String(length=100), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('purchase_url', sa.String(length=2000), nullable=True),
    sa.Column('reorder_threshold', sa.Integer(), nullable=True),
    sa.Column('purchasable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reorder_threshold IS NULL OR reorder_threshold >= 0', name='ck_parts_reorder_threshold'),
    sa.CheckConstraint('reserved >= 0', name='ck_parts_reserved'),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name='ck_parts_unit_cost'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('material_part_id', sa.Integer(), nullable=True),
    sa.Column('material_assembly_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(material_part_id IS NULL) != (material_assembly_id IS NULL)', name='ck_assembly_items_exactly_one_material'),
    sa.CheckConstraint('material_assembly_id IS NULL OR material_assembly_id != assembly_id', name='ck_assembly_items_no_self_reference'),
    sa.CheckConstraint('quantity > 0', name='ck_assembly_items_quantity'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['material_assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['material_part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assembly_items_unique_assembly', 'assembly_items', ['assembly_id', 'material_assembly_id'], unique=True, postgresql_where='material_assembly_id IS NOT NULL')
    op.create_index('ix_assembly_items_unique_part', 'assembly_items', ['assembly_id', 'material_part_id'], unique=True, postgresql_where='material_part_id IS NOT NULL')
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(component_type = 'none' AND part_id IS NULL AND assembly_id IS NULL) OR (component_type = 'part' AND part_id IS NOT NULL AND assembly_id IS NULL) OR (component_type = 'assembly' AND assembly_id IS NOT NULL AND part_id IS NULL)", name='ck_bom_items_component_consistency'),
    sa.CheckConstraint('quantity > 0', name='ck_bom_items_quantity'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_product_settings',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('matrix_layout', sa.Boolean(), nullable=False),
    sa.Column('buildable_alert_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'item_id')
    )
    op.create_table('ec_oauth_tokens',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('item_categories',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'item_id', 'category_id')
    )
    op.create_table('manual_items',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id', 'item_id')
    )
    op.create_table('manual_order_import_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_ref_column', sa.String(length=100), nullable=True),
    sa.Column('ordered_at_column', sa.String(length=100), nullable=True),
    sa.Column('last_name_column', sa.String(length=100), nullable=True),
    sa.Column('first_name_column', sa.String(length=100), nullable=True),
    sa.Column('prefecture_column', sa.String(length=100), nullable=True),
    sa.Column('address_column', sa.String(length=100), nullable=True),
    sa.Column('email_column', sa.String(length=100), nullable=True),
    sa.Column('item_id_column', sa.String(length=100), nullable=False),
    sa.Column('quantity_column', sa.String(length=100), nullable=True),
    sa.Column('variation_name_column', sa.String(length=100), nullable=True),
    sa.Column('price_column', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_manual_order_import_profiles_shop_id_name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('unique_key', sa.String(length=64), nullable=False),
    sa.Column('dispatch_status', sa.String(length=20), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_fetched', sa.Boolean(), nullable=False),
    sa.Column('stock_applied', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('prefecture', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total IS NULL OR total >= 0', name='ck_orders_total'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'unique_key', name='uq_orders_shop_id_unique_key')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('order_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_orders_quantity'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('allowed_user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allowed_user_id'], ['allowed_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('target_stock', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_stock >= 0', name='ck_stock_schedules_target_stock'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_item_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_item_id', sa.Integer(), nullable=False),
    sa.Column('selector_type', sa.String(length=20), nullable=False),
    sa.Column('selector_id', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('choice_name', sa.String(length=255), nullable=True),
    sa.Column('group_order', sa.Integer(), nullable=True),
    sa.Column('choice_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("selector_type IN ('option', 'variation')", name='ck_bom_item_conditions_selector_type'),
    sa.ForeignKeyConstraint(['bom_item_id'], ['bom_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('reservation_skipped', 'assembly_stock_shortfall', 'stock_operation_failed', 'retention_cleanup', 'auth_error')", name='ck_event_logs_category'),
    sa.CheckConstraint("level IN ('info', 'warning', 'error')", name='ck_event_logs_level'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_item_variations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id', 'item_id'], ['manual_items.shop_id', 'manual_items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('variation_id', sa.String(length=64), nullable=True),
    sa.Column('variation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_order_item_id', sa.String(length=64), nullable=True),
    sa.Column('reservation_applied', sa.Boolean(), nullable=False),
    sa.Column('picked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total IS NULL OR total >= 0', name='ck_order_items_total'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('manual_edit', 'add_stock', 'purchase_order_received', 'purchase_order_receive_undone', 'order_consumed', 'order_dispatch_undone', 'assembly_build', 'assembly_build_material', 'manual_item_consumed')", name='ck_stock_movements_reason'),
    sa.CheckConstraint('(part_id IS NULL) != (assembly_id IS NULL)', name='ck_stock_movements_exactly_one_component'),
    sa.CheckConstraint('quantity != 0', name='ck_stock_movements_quantity_nonzero'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_assembly', 'stock_movements', ['assembly_id'], unique=False)
    op.create_index('ix_stock_movements_part', 'stock_movements', ['part_id'], unique=False)
    op.create_table('order_item_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.String(length=64), nullable=False),
    sa.Column('option_variation_id', sa.String(length=64), nullable=False),
    sa.Column('option_name', sa.String(length=255), nullable=True),
    sa.Column('option_value', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_part_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(part_id IS NULL) != (assembly_id IS NULL)', name='ck_order_part_reservations_exactly_one_component'),
    sa.CheckConstraint('quantity > 0', name='ck_order_part_reservations_quantity'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_part_reservations_order_assembly', 'order_part_reservations', ['order_id', 'assembly_id'], unique=False)
    op.create_index('ix_order_part_reservations_order_part', 'order_part_reservations', ['order_id', 'part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_part_reservations_order_part', table_name='order_part_reservations')
    op.drop_index('ix_order_part_reservations_order_assembly', table_name='order_part_reservations')
    op.drop_table('order_part_reservations')
    op.drop_table('order_item_options')
    op.drop_index('ix_stock_movements_part', table_name='stock_movements')
    op.drop_index('ix_stock_movements_assembly', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('order_items')
    op.drop_table('manual_item_variations')
    op.drop_table('event_logs')
    op.drop_table('bom_item_conditions')
    op.drop_table('stock_schedules')
    op.drop_table('sessions')
    op.drop_table('purchase_orders')
    op.drop_table('orders')
    op.drop_table('manual_order_import_profiles')
    op.drop_table('manual_items')
    op.drop_table('item_categories')
    op.drop_table('ec_oauth_tokens')
    op.drop_table('bom_product_settings')
    op.drop_table('bom_items')
    op.drop_index('ix_assembly_items_unique_part', table_name='assembly_items', postgresql_where='material_part_id IS NOT NULL')
    op.drop_index('ix_assembly_items_unique_assembly', table_name='assembly_items', postgresql_where='material_assembly_id IS NOT NULL')
    op.drop_table('assembly_items')
    op.drop_table('shops')
    op.drop_table('parts')
    op.drop_table('notification_alert_states')
    op.drop_table('assemblies')
    op.drop_table('app_settings')
    op.drop_table('api_keys')
    op.drop_table('allowed_users')
    # ### end Alembic commands ###
